kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-vol
  labels:
    app: vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadeWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
   path: /mnt/data